app/models.py
from . import db,login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash


class User(db.Model,UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255),unique= True,nullable=False)#why
    username =db.Column(db.String(255),unique =True,nullable=False)
    password_hash = db.Column(db.String())
    bio=db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    booking=db.relationship('Book', backref='book',lazy='dynamic')
    booking=db.relationship('Session', backref='slots',lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)
        
    def save_user(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.add(self)
        db.session.commit()

    def __repr__ (self):
        return f'User{self.username}'
    

class Book(db.Model):
    __tablename__ = 'book'

    id = db.Column(db.Integer,primary_key = True)
    name= db.Column(db.String(60),nullable=False)
    day=db.Column(db.DateTime,default=datetime.utcnow)
    tday=db.Column(db.String(255),nullable=False)
    user_id= db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_book(self):
        db.session.add(self)
        db.session.commit()

    def __repr__(self):
        return f'Book {self.name}'

class Session(db.Model):

    __tablename__ = 'slots'
      
    id=db.Column(db.Integer,primary_key=True)
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    book_id=db.Column(db.Integer,db.ForeignKey('book.id'))
    slot=db.Column(db.Integer,nullable=False)
    



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SelectField,TextAreaField,SubmitField,IntegerField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class BookForm(FlaskForm):
    name = StringField('Name',validators=[Required()])
    tday = SelectField('Time of the Day',choices=[('Morning','Morning'),('Noon','Noon'),('Evening','Evening')],validators = [Required()])
    submit= SubmitField('Book')

class SlotForm(FlaskForm):
    slot=IntegerField('Book Slots', validators=[Required()])

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    # login_manager.session_protection = 'strong' ken code
    # login_manager.login_view = 'auth.login'
    login_manager.login_message = "You must be logged in to access this page."


    # Initializing flask extension
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # configure UploadSet
    configure_uploads(app,photos)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from.auth import auth as auth_blueprint
    #app.register_blueprint(auth_blueprint) ken code
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    # Will add the views and forms

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,redirect,url_for,abort ,request #Takes in the name of the template.
from flask_login import login_required,current_user
from ..models import User,Book
from .. import db,photos
from . import main
from .forms import UpdateProfile,BookForm


from flask_bootstrap import Bootstrap

@main.route('/')
def index():
     

    return render_template ('index.html')

@main.route('/book',methods=['GET','POST'])
@login_required
def book():
    form=BookForm()
    if form.validate_on_submit():
        name=form.name.data
        tday=form.tday.data
        user_id=current_user

        new_book= Book(name=name,tday=tday,user_id=current_user._get_current_object().id)
        
        new_book.save_book()
        return redirect(url_for('main.index'))
    return render_template('book/book.html',form=form)

@main.route('/gallery')
def gallery():

    return render_template('gallery.html')

@main.route('/about_us')
def about():

    return render_template('about-us.html')


# @main.route('/book')
# @login_required
# def book():

#     return render_template('book.html')

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/views.py
from flask import render_template    #Takes in the name of the template.
from app import app

#Views
@app.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    return render_template('index.html')

app/templates/about-us.html
{% extends 'base.html' %}
{%block content%}
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='css/about.css')}}">
<div class="jumbotron text-center"
    style="background-color: #75caf5; color: #ffffff; padding: 55px 25px; font-family: 'Gloria Hallelujah', cursive;">
    <h1>About-Us</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">

    
    <div class="row">
        <div class="col-md-4">
            <div class="containers">
                <img src="../static/photos/me.JPG" alt="Avatar" class="image" style="width:170px;height:170px;">

                <div class="overlay">
                    <div class="text">kenneth</div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="containers">
                <img src="../static/photos/trevoh.jpeg" alt="Avatar" class="image" style="width:170px;height:170px;">

                <div class="overlay">
                    <div class="text">trevor</div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="containers">
                <img src="../static/photos/greg.jpeg" alt="Avatar" class="image" style="width:170px;height:170px;">

                <div class="overlay">
                    <div class="text">greg</div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pool</title>
</head>
{% block styles %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">


{% endblock %}
<body>
    {% block navbar %}
        {% include "navbar.html" %}
        {% endblock %}
        {% block content %}
        
        {% endblock %}
<!--botton-->
        <div class="row mt-5">
            <div class="col-md-12 col-lg-12 col-sm-12 ">
                <div class="jumbotron c mt-5" style="background-color: #75caf5;">
          
                    <section class="mail" id="contact">
                      <div class="container pt-3">
                          <div class="middle-heading1 text-center mb-5">
                              <h3 id="h3contact">contact us</h3>
                          </div>
                          <div class="row form">
                              <div class="col-lg-8  cont">
                                  <form action="#" method="post">
                                      <div class="row">
                                          <div class="col-md-6 wthree_contact_left_grid pr-md-0">
                                              <div class="form-group">
                                                  <input type="text" name="name" class="mb-4 form-control"
                                                      placeholder="Name" required="">
                                              </div>
                                              <div class="form-group">
                                                  <input type="email" name="email" class="mb-4 form-control"
                                                      placeholder="Email" required="">
                                              </div>
                                          </div>
                                          <div class="col-md-6 wthree_contact_left_grid">
                                              <div class="form-group">
                                                  <input type="text" name="phone number" class="mb-4 form-control"
                                                      placeholder="Phone Number" required="">
                                              </div>
                                              <div class="form-group">
                                                  <input type="text" name="subject" class="mb-4 form-control"
                                                      placeholder="Subject" required="">
                                              </div>
                                          </div>
                                      </div>
                                      <div class="form-group">
                                          <textarea name="message" placeholder="Message" class="form-control"
                                              required=""></textarea>
                                      </div>
                                      <div class="submit-buttons">
                                          <input type="submit" value="Submit">
                                      </div>
                                  </form>
                              </div>
                              <div class="col-lg-4 contact-info">
                                  <div class="contact-info1">
                                      <h4 class="mb-4">Address Information</h4>
                                      <p><span class="fa mr-3 fa-map-marker"></span><span>Hardy near co-operative university</span></p>
                                      <p class="phone "><span class="fa mr-3 fa-phone"></span>Phone : +254716613990 </p>
                                      <p class="phone "><span class="fa mr-3 fa-phone"></span>Call us at +254716613980 </p>
                                      <p><span class="fa mr-3 fa-envelope"></span>Email : <a
                                              href="mailto:info@cookitmail.com">info@horizonpool@gmail.com</a></p>
                                  </div>
                              </div>
                          </div>
                      </div>
                    </section>
                    </section>
                    </div>
            </div>
        </div>

        <!--contact us icons-->
<div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 footer text-center">
                <i class="fab fa-whatsapp" style="font-size:30px; color:gray;"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fab fa-instagram" style="font-size:30px; color:gray;"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fab fa-twitter" style="font-size:30px; color:gray;"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fab fa-linkedin-in" style="font-size:30px; color:gray;"></i>&nbsp;&nbsp;&nbsp;&nbsp;
                <i class="fab fa-facebook" style="font-size:30px; color:gray;"></i>&nbsp;&nbsp;&nbsp;&nbsp;
            </div>
</div>
</body>
</html>

app/templates/book/book.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
 
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<div class="jumbotron text-center" style="background-color: #75caf5; color: #ffffff; padding: 55px 25px; font-family: 'Gloria Hallelujah', cursive;">
    <h1>BOOK</h1>
</div>



<div class="mt-5">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h2 class="text-center">Book Here</h2>
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-4"></div>
    </div>
</div>


<div class="row">
{% for blog_post in book %}
<div class="card p-3 ml-3 mt-4" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{ blog_post.name}}</h5>
      <h5 class="card-title">{{ blog_post.tday}}</h5>
      <button type="button" class="btn btn-primary btn-lg">{{blog_post.tday}}</button>

    </div>
  </div>
  {% endfor %}
</div>
{%endblock%}

app/templates/fourowfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/gallery.html
{% extends 'base.html'%}

{%block content%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">

<div class="jumbotron text-center" style="background-color: #75caf5; color: #ffffff; padding: 55px 25px; font-family: 'Gloria Hallelujah', cursive;">
    <h1>Gallery</h1>
</div>
<div class="container-fluid" style="font-family: 'Indie+Flower', cursive;">
    <div class="row pt-5">
 
        <div class="col-lg-3 col-md-6 work pic1">
            <img src="../static/photos/g1.jpg " class="img-fluid">
            <p class="pd txt1">Hey this is this ultimate swimming pool experience</p>
      
            
        </div>
      
        <div class="col-lg-3 col-md-6 work pic2">
            <img src="../static/photos/g3.jpg" class="img-fluid">
            <p class="pd txt2">Bring your kids along for more fun </p>
      
        </div>
      
        <div class="col-lg-3 col-md-6 pt work pic3">
      
            <img src="../static/photos/g6.jpg" class="img-fluid">
                  <p class="pd txt3">Indoor swimming is also available </p>
        </div>
      
      
        <div class="col-lg-3 col-md-6 work pic4">
      
            <img src="../static/photos/gal4.jpg" class="img-fluid">
            <p class="pd txt4">Hot tubs anyone? </p>
        </div>
      <!--row2-->
      
        <div class="col-lg-3 col-md-6 pt-5 work pic5">
            <img src="../static/photos/g2.jpg " class="img-fluid">
            <p class="pd txt5">Swim in the sun all day! </p>
      
        </div>
      
        <div class="col-lg-3 col-md-6 pt-5 work pic6">
            <img src="../static/photos/gal3.jpg" class="img-fluid">
            <p class="pd txt6">Special areas allocated for your child's safety </p>
        </div>
      
        <div class="col-lg-3 col-md-6 pt-5 work pic7">
            <img src="../static/photos/G.jpg" class="img-fluid">
            <p class="pd txt7">Olympic size swimming pools for the athletes</p>
        </div>
      
        <div class="col-lg-3 col-md-6 pt-5 work pic8">
            <img src="../static/photos/GA.jpg" class="img-fluid">
      
            <p class="pd txt8">FRESHIG UP IS ESSENTIAL</p>
        </div>
      <!--row3-->
       
      <div class="col-lg-3 col-md-6 pt-5 work pic9">
          <img src="../static/photos/P3.jpg " class="img-fluid">
          <p class="pd txt9"> With mother nature in the background.</p>
      </div>
      
      <div class="col-lg-3 col-md-6 pt-5 work pic10">
          <img src="../static/photos/P4.jpg" class="img-fluid">
      
          <p class="pd txt10">Perfect for a romantic evening swim</p>
      </div>
      
      <div class="col-lg-3 col-md-6 pt-5 work pic11">
          <img src="../static/photos/pico.jpg" class="img-fluid">
          <p class="pd txt11">For our pro user,,wanna enjoy infinity pools? </p>
      </div>
      
      <div class="col-lg-3 col-md-6 pt-5 work pic12">
          <img src="../static/photos/PP.jpg" class="img-fluid">
      
         
          <p class="pd txt12">luxury is in house </p>
      </div>
      
      </div>
    
</div>
{%endblock%}

app/templates/index.html
{% extends "base.html"%}
{% block styles %}
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link href="https://fonts.googleapis.com/css?family=Gloria+Hallelujah&display=swap" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.9/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}">
<link href="https://fonts.googleapis.com/css?family=Gelasio&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Pacifico&display=swap" rel="stylesheet">
{%endblock%}
{%block content%}


 <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 ">
            <div class="jumbotron text-center" style="background-color: #75caf5; color:#ffffff; font-family: 'Gloria Hallelujah', cursive;">
                <h1 class>HORIZON POOLS</h1>
            </div>
            <!-- <div class="col-md-12 col-lg-12 col-sm-12"> -->
                <div class="one">
                    <h4>Horizon pools is the place to be</h4> 
                    </div>
                    
           </div>
    </div>
    <!--cards-->
<div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12">
        <div class="elabo text-center mt-4">
            <h3>ELABORATION</h3>
            <p>Its the great home for the real divers, come along and feel the environment, of beauty and joy. No limitation just you and the fun of your life in our heaven</p></br>
            <p id="motto">sweet great Horizon for all</p>
        </div>
    </div>
</div>
    

        </div>  
          

   
{%endblock%}

app/templates/navbar.html
{%block content%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><i class="fas fa-swimmer"> Horizon</i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarNav"
        aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.index')}}">Home</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.about')}}">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.gallery')}}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('main.book')}}">Book</a>
            </li>
        </ul>
    </div>
    <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <!-- <li style="color:white;padding:15px;">{{current_user.username}}</li> -->
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}"><i class="fas fa-user-circle" style="font-size:20px;"></i></a></li>&nbsp;&nbsp;
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <a href="{{url_for('auth.login')}}"><i class="fas fa-sign-in-alt" style="float: right;">&nbsp; Log In</i></a>
        {%endif%}
    </ul>
   

</nav>


{%endblock%}

app/templates/profile/profile.html
{% extends 'base.html'%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/profile.css')}}">
{% endblock %}

{% block content %}

<div class="jumbotron text-center" style="background-color: #75caf5; color: #ffffff; padding: 55px 25px; font-family: 'Gloria Hallelujah', cursive;">
  <h1>Profile</h1>
</div>

<div class="container">
<div class="row">
  <div class="col-md-4">

  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    <h3> {{user.username| capitalize}} </h3>
    <h3>{{user.email}}</h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}

    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="jumbotron text-center" style="background-color: #75caf5; color: #ffffff; padding: 55px 25px; font-family: 'Gloria Hallelujah', cursive;">
  <h1>Update Profile</h1>
</div>

<div class="container">
  {{wtf.quick_form(form)}}
{% endblock %}